[platformio]
description = AirDrum sender
default_envs = ESP32_Dev_Server
src_dir = .

[env]
monitor_speed = 115200
framework = arduino
lib_deps =
    Wire
    sui77/rc-switch@^2.6.4
    ESP32Async/ESPAsyncWebServer
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson@^7.4.1
    wollewald/MPU9250_WE @ ^1.2.17
    marian-craciunescu/ESP32Ping @ ^1.7

build_flags = 
    -I lib

[env:ESP32_Dev_Server]
platform = espressif32
board = esp32dev
upload_speed = 921600 # uncomment if you have issues with uploading
build_src_filter = +<server/src/> -<client/src/>

[env:Nano_Server]
platform = atmelavr
board = nanoatmega328new
build_src_filter = +<server/src/> -<client/src/>

[env:ESP32_Dev_Client]
platform = espressif32
board = esp32dev
upload_speed = 921600 # uncomment if you have issues with uploading
build_src_filter = -<server/src/> +<client/src/>

[env:Nano_Client]
platform = atmelavr
board = nanoatmega328new
build_src_filter = -<server/src/> +<client/src/>
