[platformio]
description = AirDrum sender
default_envs = esp32devServer
src_dir = .

[env]
monitor_speed = 115200
framework = arduino
lib_deps =
    Wire
    sui77/rc-switch@^2.6.4
    ESP32Async/ESPAsyncWebServer
    wollewald/MPU9250_WE @ ^1.2.17
build_flags = 
    -I lib

[env:esp32devServer]
platform = espressif32
board = esp32dev
upload_speed = 921600 # uncomment if you have issues with uploading
build_src_filter = +<server/src/> -<client/src/>

[env:nanoServer]
platform = atmelavr
board = nanoatmega328new
build_src_filter = +<server/src/> -<client/src/>

[env:esp32devClient]
platform = espressif32
board = esp32dev
upload_speed = 921600 # uncomment if you have issues with uploading
build_src_filter = -<server/src/> +<client/src/>

[env:nanoClient]
platform = atmelavr
board = nanoatmega328new
build_src_filter = -<server/src/> +<client/src/>
